name: BuildPackage

on: [workflow_dispatch,push]

jobs:

  buildAllPackage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'corretto'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version: 1.6.10
          
      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew package
          
      - name: Upload Windows Package
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/compose/binaries/main/msi
          
      - name: Upload Linux Package
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/compose/binaries/main/deb
          
      - name: Upload macOS Package
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./build/compose/binaries/main/dmg
